const doctors = [
  {
    name: "Dr. John Smith",
    title: "Cardiologist & Heart Specialist",
    location: "New York, USA",
    availability: true,
    hourlyRate: "20",
    rating: 4.9,
    maxRating: 5.0,
    skills: ["Cardiology", "Heart Surgery", "Patient Care"],
    description:
      "Dr. John Smith has over 15 years of experience specializing in heart diseases and cardiac surgery. He has successfully performed numerous life-saving procedures and is recognized for his expertise in heart disease management and prevention.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    bio: "Dr. John Smith is known for his compassionate approach to patient care and his extensive expertise in heart surgery. He takes pride in making complex medical information accessible to patients and their families.",
  },
  {
    name: "Dr. Emma Johnson",
    title: "Pediatrician & Child Health Expert",
    location: "London, UK",
    availability: false,
    hourlyRate: "25",
    rating: 4.7,
    maxRating: 5.0,
    skills: ["Pediatrics", "Vaccination", "Child Nutrition"],
    description:
      "Dr. Emma Johnson is a well-known pediatrician with a passion for child healthcare and nutrition. With over a decade of experience, she has helped thousands of young patients lead healthier lives through early diagnosis and treatment.",
    imageUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    bio: "Dr. Emma Johnson believes in the power of prevention and early intervention to ensure children lead healthy, happy lives. She is an advocate for child nutrition and wellness education.",
  },
  {
    name: "Dr. Michael Lee",
    title: "Orthopedic Surgeon",
    location: "Sydney, Australia",
    availability: true,
    hourlyRate: "30",
    rating: 4.8,
    maxRating: 5.0,
    skills: ["Bone Surgery", "Joint Replacement", "Sports Injuries"],
    description:
      "Dr. Michael Lee is an expert in orthopedic surgery, focusing on joint replacements and sports injury treatments. With a track record of over 500 successful surgeries, he is a trusted name in musculoskeletal health care.",
    imageUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    bio: "Dr. Michael Lee is dedicated to improving mobility and quality of life for patients through precise surgeries and tailored rehabilitation plans. He is also actively involved in sports injury prevention research.",
  },
  {
    name: "Dr. Sophia Brown",
    title: "Dermatologist & Skin Specialist",
    location: "Toronto, Canada",
    availability: true,
    hourlyRate: "18",
    rating: 4.6,
    maxRating: 5.0,
    skills: ["Acne Treatment", "Skin Rejuvenation", "Laser Therapy"],
    description:
      "Dr. Sophia Brown is a skincare specialist known for her innovative acne treatment methods. She has helped countless patients achieve healthier skin through advanced dermatological procedures.",
    imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    bio: "Dr. Sophia Brown is passionate about improving her patients' self-esteem and confidence through advanced skincare treatments. She is committed to staying at the forefront of dermatology.",
  },
  {
    name: "Dr. William Martinez",
    title: "Neurologist & Brain Specialist",
    location: "Berlin, Germany",
    availability: false,
    hourlyRate: "40",
    rating: 4.9,
    maxRating: 5.0,
    skills: ["Brain Surgery", "Epilepsy Treatment", "Neurotherapy"],
    description:
      "Dr. William Martinez specializes in brain disorders and has performed over 500 successful surgeries. His research on neurological diseases has contributed significantly to modern neurotherapy.",
    imageUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    bio: "Dr. William Martinez's work in brain health has revolutionized treatments for neurological disorders. He is a strong advocate for mental health awareness and research.",
  },
  {
    name: "Dr. Olivia Taylor",
    title: "General Physician",
    location: "Mumbai, India",
    availability: true,
    hourlyRate: "12",
    rating: 4.5,
    maxRating: 5.0,
    skills: ["General Checkup", "Preventive Care", "Diagnosis"],
    description:
      "Dr. Olivia Taylor is a general practitioner focused on preventive care and holistic health. She has a decade of experience treating various medical conditions and providing comprehensive patient care.",
    imageUrl: "https://randomuser.me/api/portraits/women/6.jpg",
    bio: "Dr. Olivia Taylor emphasizes the importance of regular health checkups and lifestyle changes for maintaining long-term health. She is dedicated to providing care that addresses the root causes of medical issues.",
  },
  {
    name: "Dr. Daniel Wilson",
    title: "Endocrinologist & Diabetes Specialist",
    location: "Paris, France",
    availability: true,
    hourlyRate: "35",
    rating: 4.8,
    maxRating: 5.0,
    skills: ["Diabetes Management", "Hormone Therapy", "Thyroid Treatment"],
    description:
      "Dr. Daniel Wilson is a leading expert in diabetes and endocrine disorders. His research and treatments have greatly improved the quality of life for many diabetes patients worldwide.",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    bio: "Dr. Daniel Wilson works tirelessly to improve treatments for diabetes and hormone disorders. He is passionate about patient education and advocates for lifestyle management in preventing chronic illnesses.",
  },
  {
    name: "Dr. Ava Davis",
    title: "Psychiatrist & Mental Health Expert",
    location: "Dubai, UAE",
    availability: false,
    hourlyRate: "50",
    rating: 4.9,
    maxRating: 5.0,
    skills: [
      "Anxiety Treatment",
      "Depression Therapy",
      "Cognitive Behavioral Therapy",
    ],
    description:
      "Dr. Ava Davis helps individuals overcome anxiety and depression with her advanced therapy techniques. She has over 20 years of experience in mental health counseling and therapy.",
    imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
    bio: "Dr. Ava Davis is a compassionate psychiatrist who is committed to helping patients find peace and stability through therapy. She specializes in personalized mental health treatment plans.",
  },
  {
    name: "Dr. James Anderson",
    title: "Oncologist & Cancer Specialist",
    location: "Singapore",
    availability: true,
    hourlyRate: "60",
    rating: 5.0,
    maxRating: 5.0,
    skills: ["Cancer Treatment", "Chemotherapy", "Radiation Therapy"],
    description:
      "Dr. James Anderson is an oncologist known for his groundbreaking cancer treatment methods. He has led pioneering research in chemotherapy and radiation therapy techniques.",
    imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    bio: "Dr. James Anderson is renowned for his work in cancer research and patient advocacy. He is dedicated to advancing cancer treatments and providing compassionate care to his patients.",
  },
  {
    name: "Dr. Mia Thompson",
    title: "Gynecologist & Women's Health Expert",
    location: "Tokyo, Japan",
    availability: true,
    hourlyRate: "22",
    rating: 4.7,
    maxRating: 5.0,
    skills: ["Prenatal Care", "Infertility Treatment", "Hormone Therapy"],
    description:
      "Dr. Mia Thompson specializes in women’s reproductive health and wellness. She is dedicated to improving women's healthcare through innovative treatments and prenatal care.",
    imageUrl: "https://randomuser.me/api/portraits/women/10.jpg",
    bio: "Dr. Mia Thompson is committed to improving women’s health and wellness. She advocates for holistic approaches to care and is dedicated to providing personalized and empathetic treatment.",
  },
];

export default doctors;
